[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "evaluation_scripts"
authors = [{name = "Tobias Stark", email = "tobias.stark@apex.ai"}]
dynamic = ["version", "description"]
